#!/bin/bash

#takes 1 argument: the path to the file and its name on the pi
read -r -p "This script deletes the video(s) you specify from all the cameras, are you sure? [Y/n]" response
 response=${response,,} # tolower

 if [[ $response =~ ^(yes|y| ) ]]; then
	echo -n "Enter trial name, then press [ENTER]:"
	read identifier

	USERNAME=pi

	while read line; do
	    HOSTNAME=$line
	    IFS='.'
	    
	    read -ra ADDR <<< "$line"
	    
	    SCRIPT="rm ${identifier}_${ADDR[0]}.h264"
	    
	    ssh -l ${USERNAME}@${HOSTNAME} "${SCRIPT}" &
	done < ip_addr_book.txt
        
 fi

