#!/bin/bash

#takes 1 argument: the path to the file and its name on the pi
read -r -p "This script deletes the video(s) you specify from all the cameras, are you sure? [Y/n]" response
 response=${response,,} # tolower

 if [[ $response =~ ^(yes|y| ) ]]; then
	echo -n "Either provide the complete file name or the first few letters followed by a * (e.g. TRIAL*) to erase similarily named files, then press [ENTER]:"
	read identifier

	USERNAME=pi
	SCRIPT="rm $identifier"
	
	while read line; do
	    HOSTNAME=$line
	    ssh -l ${USERNAME} ${HOSTNAME} "${SCRIPT}" &
	done < ip_addr_book.txt
        
 fi

