#! /bin/bash



	echo -n "Enter file name with path (can use * on long file names), then press [ENTER]:"
	read name
	echo -n "Enter destination directory, then press [ENTER]:"
	read identifier

       while read line; do

            HOSTNAME=$line
            USERNAME=pi
            scp ${USERNAME}@${HOSTNAME}:$name $identifier  &


        done < ip_addr_book.txt
        
 	echo "Wait for files to complete download before deleting them with delete_videos script"






