#! /bin/bash

#takes 1 argument: the file to download (with its directory on the pi)

 read -r -p "Are you sure? [Y/n]" response
 response=${response,,} # tolower
 if [[ $response =~ ^(yes|y| ) ]]; then
       while read line; do

            HOSTNAME=$line
            USERNAME=pi
            scp ${USERNAME}@${HOSTNAME}:$1 /home/jason/Desktop/151004B  &


        done < ip_addr_book.txt
        
 fi






