#!/bin/bash
read -r -p "Running this script will abort all recording, are you sure? [Y/n]" response
 response=${response,,} # tolower
 if [[ $response =~ ^(yes|y| ) ]]; then
	USERNAME=pi
	SCRIPT="pkill python"
	while read line; do
	    HOSTNAME=$line
	    ssh -l ${USERNAME} ${HOSTNAME} "${SCRIPT}" &
	    
	done < ip_addr_book.txt
echo Capture has been aborted on all cameras
fi
