#!/bin/bash


#tm=$(date +"%H:%M:%S:%N")

#TIME="sudo date +%H:%M:%S:%N --set=$tm"

	while read line; do
	    tm=$(date +"%H:%M:%S")
	    TIME="sudo date +%H:%M:%S --set=$tm"
            USERNAME=pi
	    HOSTNAME=$line
            ssh -l ${USERNAME} ${HOSTNAME} "${TIME}" &
            echo Time on Rpi $line is $tm
        done < ip_addr_book.txt

exit 1

